import { Component } from '@angular/core';
import { IMenuItem } from 'src/app/interfaces/menu/menu-item';

@Component({
  selector: 'app-tile-view-demo-page',
  templateUrl: './tile-view-demo-page.component.html',
  styleUrls: ['./tile-view-demo-page.component.scss']
})
export class TileViewDemoPageComponent {
    treeViewDataSourceTile: IMenuItem[] = [
        {
          "id": "ddfb8117-89c3-4b6e-bf5b-dd725e456c6b",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 0,
          "parentId": null,
          "code": "01",
          "caption": "Общие данные",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": true,
          "visibleCondition": null,
          "enableCondition": null,
          "pictureId": null,
          "pictureData": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAF/SURBVHgBpVPbbcIwFL3XTf67QbNB0w0SFoB+8pAKE5ROEJig2QBQAvmFBQpsABOUbsAvJNg9dgGFkA9Qj2TJvu/HMVMBXhR5xFxl5hop5RzFK7xXUoj+ol7f5O357DgYPLJl9eD8pphDodTwq9X6Mbrx2KXDwUWQgB8epnK36y86ne05gHG27bnJst9/nJRX1cGObDuAk6fS1D/b+VEUenH8STfCj+NhZTIx9paXJA5lWZXS9KVoWEmSQErpLprN17wc2buo5BvzmgkhZYCee2VlyyxbkpSjolzbot1QDxuzUi4u69JahdjibMpU2MiIlaoJ3HWJKypH9XiuYNbJ7Aj6JwSibCpx/ER3wnADBNMzmErmNt0PV+kAoOsMw+gaklxjezyX2TXxiAKsvv8nAInQxoBuRJ54lpEgkgKVNbvyPC/NbNshrs/w8bXs4jMZnuMXamKhtfVpvdA5wrLakL+j76FOePGZClkcHUgPCUrXCLEpPWwWYjpvNJZ5+1/X37oLLz868QAAAABJRU5ErkJggg==",
          "pictureKey": null,
          "frameId": "76d5c4b6-6169-4a24-aad5-53b82b252a51",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 1,
          "selectMenuItemId": null,
          "toolBarPosition": 1,
          "toolBarStyle": 0,
          "items": [
            {
              "id": "26d0747c-a0e5-406a-8b21-2928c84969a3",
              "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
              "type": 2,
              "parentId": "ddfb8117-89c3-4b6e-bf5b-dd725e456c6b",
              "code": "01.02",
              "caption": "История изменения данных",
              "description": null,
              "newGroup": false,
              "toolTip": null,
              "enable": true,
              "visible": true,
              "visibleCondition": null,
              "enableCondition": null,
              "pictureId": null,
              "pictureData": null,
              "pictureKey": null,
              "frameId": "4510f896-8e75-48bd-8a8b-ec7d59e273a4",
              "frameType": 0,
              "kbFrameType": 3,
              "commandId": null,
              "multiRun": false,
              "expanded": false,
              "positionOrder": 2,
              "selectMenuItemId": null,
              "toolBarPosition": 3,
              "toolBarStyle": 0,
              "items": [
                {
                    "id": "66d0747c-a0e5-406a-8b21-2928c84969a3",
                    "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
                    "type": 2,
                    "parentId": "ddfb8117-89c3-4b6e-bf5b-dd725e456c6b",
                    "code": "01.02",
                    "caption": "История изменения данных вложенный",
                    "description": null,
                    "newGroup": false,
                    "toolTip": null,
                    "enable": true,
                    "visible": true,
                    "visibleCondition": null,
                    "enableCondition": null,
                    "pictureId": null,
                    "pictureData": null,
                    "pictureKey": null,
                    "frameId": "4510f896-8e75-48bd-8a8b-ec7d59e273a4",
                    "frameType": 0,
                    "kbFrameType": 3,
                    "commandId": null,
                    "multiRun": false,
                    "expanded": false,
                    "positionOrder": 2,
                    "selectMenuItemId": null,
                    "toolBarPosition": 3,
                    "toolBarStyle": 0,
                    "items": [
                      
                    ],
                },
                {
                    "id": "77d0747c-a0e5-406a-8b21-2928c84969a3",
                    "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
                    "type": 2,
                    "parentId": "ddfb8117-89c3-4b6e-bf5b-dd725e456c6b",
                    "code": "01.02",
                    "caption": "История изменения данных вложенный 2",
                    "description": null,
                    "newGroup": false,
                    "toolTip": null,
                    "enable": true,
                    "visible": true,
                    "visibleCondition": null,
                    "enableCondition": null,
                    "pictureId": null,
                    "pictureData": null,
                    "pictureKey": null,
                    "frameId": "4510f896-8e75-48bd-8a8b-ec7d59e273a4",
                    "frameType": 0,
                    "kbFrameType": 3,
                    "commandId": null,
                    "multiRun": false,
                    "expanded": false,
                    "positionOrder": 2,
                    "selectMenuItemId": null,
                    "toolBarPosition": 3,
                    "toolBarStyle": 0,
                    "items": [
                      
                    ],
                }
              ],
              "permissions": null
            },
            {
                "id": "26d0747c-a0e5-406a-8b21-2928c84969a3",
                "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
                "type": 2,
                "parentId": "ddfb8117-89c3-4b6e-bf5b-dd725e456c6b",
                "code": "01.02",
                "caption": "История изменения данных 2",
                "description": null,
                "newGroup": false,
                "toolTip": null,
                "enable": true,
                "visible": true,
                "visibleCondition": null,
                "enableCondition": null,
                "pictureId": null,
                "pictureData": null,
                "pictureKey": null,
                "frameId": "4510f896-8e75-48bd-8a8b-ec7d59e273a4",
                "frameType": 0,
                "kbFrameType": 3,
                "commandId": null,
                "multiRun": false,
                "expanded": false,
                "positionOrder": 2,
                "selectMenuItemId": null,
                "toolBarPosition": 3,
                "toolBarStyle": 0,
                "items": [],
                "permissions": null
              }
          ],
          "permissions": null,
          "selected": true
        },
        {
          "id": "9e1cab06-8843-416d-991e-8cc3fbdcd6e5",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 0,
          "parentId": null,
          "code": "03",
          "caption": "Характеристики сервера",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": false,
          "visibleCondition": "'[IdEqType]' = '4'",
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "6d178f76-b8d5-4dc5-939e-3159b4cfdfeb",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 3,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [
            {
              "id": "ffb3dd82-cd05-40f9-a5df-063c13ccfcd5",
              "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
              "type": 2,
              "parentId": "9e1cab06-8843-416d-991e-8cc3fbdcd6e5",
              "code": "03.01",
              "caption": "Изменить",
              "description": null,
              "newGroup": false,
              "toolTip": null,
              "enable": true,
              "visible": true,
              "visibleCondition": null,
              "enableCondition": null,
              "pictureId": null,
              "pictureData": null,
              "pictureKey": null,
              "frameId": null,
              "frameType": 3,
              "kbFrameType": 4,
              "commandId": "97b178f6-5fc0-4542-922b-613dd01993cc",
              "multiRun": false,
              "expanded": false,
              "positionOrder": 1,
              "selectMenuItemId": null,
              "toolBarPosition": 3,
              "toolBarStyle": 0,
              "items": [],
              "permissions": null
            }
          ],
          "permissions": null
        },
        {
          "id": "13c280cc-d300-4ace-9324-63f60842feb3",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 0,
          "parentId": null,
          "code": "04",
          "caption": "Характеристики внешнего сервера",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": false,
          "visibleCondition": "'[IdEqType]' = '22'",
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "28e3cf87-0c2f-4e30-9b43-0a955b1193be",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 4,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [
            {
              "id": "d920d267-66af-4df5-8bfc-74506d4ff89e",
              "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
              "type": 2,
              "parentId": "13c280cc-d300-4ace-9324-63f60842feb3",
              "code": "04.01",
              "caption": "Изменить",
              "description": null,
              "newGroup": false,
              "toolTip": null,
              "enable": true,
              "visible": true,
              "visibleCondition": null,
              "enableCondition": null,
              "pictureId": null,
              "pictureData": null,
              "pictureKey": null,
              "frameId": null,
              "frameType": 3,
              "kbFrameType": 4,
              "commandId": "43318a00-e774-4fca-9667-90239e4d30dc",
              "multiRun": false,
              "expanded": false,
              "positionOrder": 1,
              "selectMenuItemId": null,
              "toolBarPosition": 3,
              "toolBarStyle": 0,
              "items": [],
              "permissions": null
            }
          ],
          "permissions": null
        },
        {
          "id": "8515392b-46d4-4700-a533-ea043df9bf09",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 0,
          "parentId": null,
          "code": "05",
          "caption": "Характеристики вирт. сервера",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": false,
          "visibleCondition": "'[IdEqType]' = '10'",
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "92bb98c9-7596-42aa-84a0-501b47836642",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 5,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [
            {
              "id": "7fc39c79-2dcf-4f95-9910-04a8c09164e6",
              "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
              "type": 2,
              "parentId": "8515392b-46d4-4700-a533-ea043df9bf09",
              "code": "05.01",
              "caption": "Изменить",
              "description": null,
              "newGroup": false,
              "toolTip": null,
              "enable": true,
              "visible": true,
              "visibleCondition": null,
              "enableCondition": null,
              "pictureId": null,
              "pictureData": null,
              "pictureKey": null,
              "frameId": null,
              "frameType": 3,
              "kbFrameType": 4,
              "commandId": "a7196ef2-faa7-4105-a07f-bc5eff80c925",
              "multiRun": false,
              "expanded": false,
              "positionOrder": 1,
              "selectMenuItemId": null,
              "toolBarPosition": 3,
              "toolBarStyle": 0,
              "items": [],
              "permissions": null
            }
          ],
          "permissions": null
        },
        {
          "id": "98efc325-123a-4a81-bcf4-49822632a5b5",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 0,
          "parentId": null,
          "code": "06",
          "caption": "Характеристики системного блока и даже нескольких",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": true,
          "visibleCondition": "'[IdEqType]' = '3'",
          "enableCondition": null,
          "pictureId": null,
          "pictureData": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAF/SURBVHgBpVPbbcIwFL3XTf67QbNB0w0SFoB+8pAKE5ROEJig2QBQAvmFBQpsABOUbsAvJNg9dgGFkA9Qj2TJvu/HMVMBXhR5xFxl5hop5RzFK7xXUoj+ol7f5O357DgYPLJl9eD8pphDodTwq9X6Mbrx2KXDwUWQgB8epnK36y86ne05gHG27bnJst9/nJRX1cGObDuAk6fS1D/b+VEUenH8STfCj+NhZTIx9paXJA5lWZXS9KVoWEmSQErpLprN17wc2buo5BvzmgkhZYCee2VlyyxbkpSjolzbot1QDxuzUi4u69JahdjibMpU2MiIlaoJ3HWJKypH9XiuYNbJ7Aj6JwSibCpx/ER3wnADBNMzmErmNt0PV+kAoOsMw+gaklxjezyX2TXxiAKsvv8nAInQxoBuRJ54lpEgkgKVNbvyPC/NbNshrs/w8bXs4jMZnuMXamKhtfVpvdA5wrLakL+j76FOePGZClkcHUgPCUrXCLEpPWwWYjpvNJZ5+1/X37oLLz868QAAAABJRU5ErkJggg==",
          "pictureKey": null,
          "frameId": "9266b3e3-196a-41bd-a68b-eb47146309f8",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 6,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [
            {
              "id": "4f858d3e-26aa-47b1-8e40-1c4ff48184b3",
              "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
              "type": 2,
              "parentId": "98efc325-123a-4a81-bcf4-49822632a5b5",
              "code": "06.01",
              "caption": "Изменить",
              "description": null,
              "newGroup": false,
              "toolTip": null,
              "enable": true,
              "visible": true,
              "visibleCondition": null,
              "enableCondition": null,
              "pictureId": null,
              "pictureData": null,
              "pictureKey": null,
              "frameId": null,
              "frameType": 3,
              "kbFrameType": 4,
              "commandId": "3a915996-a75c-4d6a-b10f-9180c7c51da8",
              "multiRun": false,
              "expanded": false,
              "positionOrder": 1,
              "selectMenuItemId": null,
              "toolBarPosition": 3,
              "toolBarStyle": 0,
              "items": [],
              "permissions": null
            }
          ],
          "permissions": null
        },
        {
          "id": "2611b1b7-0c63-4453-af6c-c5cbd1e8c9eb",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 0,
          "parentId": null,
          "code": "07",
          "caption": "Характеристики ноутбука",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": false,
          "visibleCondition": "'[IdEqType]' = '5'",
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "8f85edf2-132f-4f17-ba51-78da20bc9479",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 7,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [
            {
              "id": "e9ae9893-bbe2-4dfd-bc1e-6b746096ff50",
              "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
              "type": 2,
              "parentId": "2611b1b7-0c63-4453-af6c-c5cbd1e8c9eb",
              "code": "07.01",
              "caption": "Изменить",
              "description": null,
              "newGroup": false,
              "toolTip": null,
              "enable": true,
              "visible": true,
              "visibleCondition": null,
              "enableCondition": null,
              "pictureId": null,
              "pictureData": null,
              "pictureKey": null,
              "frameId": null,
              "frameType": 3,
              "kbFrameType": 4,
              "commandId": "f2db4cca-d3d9-40f2-bd46-726673fdc54b",
              "multiRun": false,
              "expanded": false,
              "positionOrder": 1,
              "selectMenuItemId": null,
              "toolBarPosition": 3,
              "toolBarStyle": 0,
              "items": [],
              "permissions": null
            }
          ],
          "permissions": null
        },
        {
          "id": "db54a3ab-098b-473c-899b-5546c2fa1132",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 0,
          "parentId": null,
          "code": "08",
          "caption": "Характеристики монитора",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": false,
          "visibleCondition": "'[IdEqType]' = '6'",
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "d3d338ed-31c0-4ac1-9af7-02e2e6f84197",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 8,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [
            {
              "id": "7132471a-e623-4e8f-bef5-4384190e14c2",
              "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
              "type": 2,
              "parentId": "db54a3ab-098b-473c-899b-5546c2fa1132",
              "code": "08.01",
              "caption": "Изменить",
              "description": null,
              "newGroup": false,
              "toolTip": null,
              "enable": true,
              "visible": true,
              "visibleCondition": null,
              "enableCondition": null,
              "pictureId": null,
              "pictureData": null,
              "pictureKey": null,
              "frameId": null,
              "frameType": 3,
              "kbFrameType": 4,
              "commandId": "e7f82468-88db-4089-a517-c3e4fefad9f2",
              "multiRun": false,
              "expanded": false,
              "positionOrder": 1,
              "selectMenuItemId": null,
              "toolBarPosition": 3,
              "toolBarStyle": 0,
              "items": [],
              "permissions": null
            }
          ],
          "permissions": null
        },
        {
          "id": "015b3080-2e46-489e-99d3-ba1d50cca674",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 0,
          "parentId": null,
          "code": "09",
          "caption": "Характеристики МФУ",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": false,
          "visibleCondition": "'[IdEqType]' = '7'",
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "1e3fc776-3b89-4f5b-a5f2-dd00e7580345",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 9,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [
            {
              "id": "2b3252ca-93e7-4321-ba29-ffb6dcda8baa",
              "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
              "type": 2,
              "parentId": "015b3080-2e46-489e-99d3-ba1d50cca674",
              "code": "09.01",
              "caption": "Изменить",
              "description": null,
              "newGroup": false,
              "toolTip": null,
              "enable": true,
              "visible": true,
              "visibleCondition": null,
              "enableCondition": null,
              "pictureId": null,
              "pictureData": null,
              "pictureKey": null,
              "frameId": null,
              "frameType": 3,
              "kbFrameType": 4,
              "commandId": "768b027d-e4f1-482c-91a4-1abad1988c96",
              "multiRun": false,
              "expanded": false,
              "positionOrder": 1,
              "selectMenuItemId": null,
              "toolBarPosition": 3,
              "toolBarStyle": 0,
              "items": [],
              "permissions": null
            }
          ],
          "permissions": null
        },
        {
          "id": "f3a6b248-10cd-4817-99d5-8a61d8dcf251",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 0,
          "parentId": null,
          "code": "10",
          "caption": "Характеристики принтера",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": false,
          "visibleCondition": "'[IdEqType]' = '8'",
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "a8f2a328-19ea-4f54-883f-1ee8b3e83782",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 10,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [
            {
              "id": "4eed79d9-6a5b-4b19-a86a-cf4cc0f56c4e",
              "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
              "type": 2,
              "parentId": "f3a6b248-10cd-4817-99d5-8a61d8dcf251",
              "code": "10.01",
              "caption": "Изменить",
              "description": null,
              "newGroup": false,
              "toolTip": null,
              "enable": true,
              "visible": true,
              "visibleCondition": null,
              "enableCondition": null,
              "pictureId": null,
              "pictureData": null,
              "pictureKey": null,
              "frameId": null,
              "frameType": 3,
              "kbFrameType": 4,
              "commandId": "6e50c67d-6ff0-46ff-b1c9-31d9a4bc209f",
              "multiRun": false,
              "expanded": false,
              "positionOrder": 1,
              "selectMenuItemId": null,
              "toolBarPosition": 3,
              "toolBarStyle": 0,
              "items": [],
              "permissions": null
            }
          ],
          "permissions": null
        },
        {
          "id": "6abb4ad8-1fd7-452a-a312-0f32590ddbfb",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 0,
          "parentId": null,
          "code": "11",
          "caption": "Характеристики точки доступа",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": false,
          "visibleCondition": "'[IdEqType]' = '9'",
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "3bb51d05-fff9-406a-b46d-d5100e1a3ed9",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 11,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [
            {
              "id": "642f8a51-005d-48a3-a57e-00509860a02e",
              "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
              "type": 2,
              "parentId": "6abb4ad8-1fd7-452a-a312-0f32590ddbfb",
              "code": "11.01",
              "caption": "Изменить",
              "description": null,
              "newGroup": false,
              "toolTip": null,
              "enable": true,
              "visible": true,
              "visibleCondition": null,
              "enableCondition": null,
              "pictureId": null,
              "pictureData": null,
              "pictureKey": null,
              "frameId": null,
              "frameType": 3,
              "kbFrameType": 4,
              "commandId": "fd4c357c-dc6c-4f42-8ee2-01e7bd922789",
              "multiRun": false,
              "expanded": false,
              "positionOrder": 1,
              "selectMenuItemId": null,
              "toolBarPosition": 3,
              "toolBarStyle": 0,
              "items": [],
              "permissions": null
            }
          ],
          "permissions": null
        },
        {
          "id": "6ca5d658-d7b5-4655-87ac-63008981a019",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 0,
          "parentId": null,
          "code": "12",
          "caption": "Характеристики сетевого коммутатора",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": false,
          "visibleCondition": "'[IdEqType]' = '12'",
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "e32eaafb-3c3f-4f97-bf42-499a99ecb845",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 12,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [
            {
              "id": "9664d75e-0f00-4501-9c28-6fc694437eb7",
              "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
              "type": 2,
              "parentId": "6ca5d658-d7b5-4655-87ac-63008981a019",
              "code": "12.01",
              "caption": "Изменить",
              "description": null,
              "newGroup": false,
              "toolTip": null,
              "enable": true,
              "visible": true,
              "visibleCondition": null,
              "enableCondition": null,
              "pictureId": null,
              "pictureData": null,
              "pictureKey": null,
              "frameId": null,
              "frameType": 3,
              "kbFrameType": 4,
              "commandId": "833ae764-28a9-45da-82d1-03bf1e8c31b4",
              "multiRun": false,
              "expanded": false,
              "positionOrder": 1,
              "selectMenuItemId": null,
              "toolBarPosition": 3,
              "toolBarStyle": 0,
              "items": [],
              "permissions": null
            }
          ],
          "permissions": null
        },
        {
          "id": "bb894868-0df7-4c28-a34e-f80445ce6677",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 0,
          "parentId": null,
          "code": "13",
          "caption": "Характеристики проектора",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": false,
          "visibleCondition": "'[IdEqType]' = '13'",
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "0a4172f6-dfb2-46e9-892c-cb686c5120a9",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 13,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [
            {
              "id": "c4fb6fb3-666b-4323-866c-76cb68e2c58e",
              "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
              "type": 2,
              "parentId": "bb894868-0df7-4c28-a34e-f80445ce6677",
              "code": "13.01",
              "caption": "Изменить",
              "description": null,
              "newGroup": false,
              "toolTip": null,
              "enable": true,
              "visible": true,
              "visibleCondition": null,
              "enableCondition": null,
              "pictureId": null,
              "pictureData": null,
              "pictureKey": null,
              "frameId": null,
              "frameType": 3,
              "kbFrameType": 4,
              "commandId": "f63d8205-5d1d-40c7-a35b-c96166746a4d",
              "multiRun": false,
              "expanded": false,
              "positionOrder": 1,
              "selectMenuItemId": null,
              "toolBarPosition": 3,
              "toolBarStyle": 0,
              "items": [],
              "permissions": null
            }
          ],
          "permissions": null
        },
        {
          "id": "8a75b904-6655-49cd-b3fe-cdcf88ef9858",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 0,
          "parentId": null,
          "code": "14",
          "caption": "Характеристики планшетного компьютера",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": false,
          "visibleCondition": "'[IdEqType]' = '14'",
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "043c4e3e-16b7-4b4d-bec1-a5211a563334",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 14,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [
            {
              "id": "04a996be-0087-4b03-8836-c31f65968ab0",
              "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
              "type": 2,
              "parentId": "8a75b904-6655-49cd-b3fe-cdcf88ef9858",
              "code": "14.01",
              "caption": "Изменить",
              "description": null,
              "newGroup": false,
              "toolTip": null,
              "enable": true,
              "visible": true,
              "visibleCondition": null,
              "enableCondition": null,
              "pictureId": null,
              "pictureData": null,
              "pictureKey": null,
              "frameId": null,
              "frameType": 3,
              "kbFrameType": 4,
              "commandId": "563cfff4-8c0c-4c31-a3de-d324ca8c5364",
              "multiRun": false,
              "expanded": false,
              "positionOrder": 1,
              "selectMenuItemId": null,
              "toolBarPosition": 3,
              "toolBarStyle": 0,
              "items": [],
              "permissions": null
            }
          ],
          "permissions": null
        },
        {
          "id": "e6e322c2-6eb5-4981-9a33-5a46cf3b1947",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 0,
          "parentId": null,
          "code": "15",
          "caption": "Характеристики теливизора",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": false,
          "visibleCondition": "'[IdEqType]' = '15'",
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "2197e61c-af72-407c-bbdb-923130e9dbd9",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 15,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [
            {
              "id": "b9657082-b5ef-4eaf-bf46-709aa10baf2e",
              "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
              "type": 2,
              "parentId": "e6e322c2-6eb5-4981-9a33-5a46cf3b1947",
              "code": "15.01",
              "caption": "Изменить",
              "description": null,
              "newGroup": false,
              "toolTip": null,
              "enable": true,
              "visible": true,
              "visibleCondition": null,
              "enableCondition": null,
              "pictureId": null,
              "pictureData": null,
              "pictureKey": null,
              "frameId": null,
              "frameType": 3,
              "kbFrameType": 4,
              "commandId": "1c2a2e08-213c-418b-a45e-6c93bcc02597",
              "multiRun": false,
              "expanded": false,
              "positionOrder": 1,
              "selectMenuItemId": null,
              "toolBarPosition": 3,
              "toolBarStyle": 0,
              "items": [],
              "permissions": null
            }
          ],
          "permissions": null
        },
        {
          "id": "816bf0c1-bf6e-4f34-bfdd-923a98910c5b",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 0,
          "parentId": null,
          "code": "16",
          "caption": "Характеристики монтажного шкафа",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": false,
          "visibleCondition": "'[IdEqType]' = '16'",
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "538fd0ae-e3a9-4b52-9062-72d0ad3f4fbe",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 16,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [
            {
              "id": "fdec469b-2e96-4136-b09a-6e48465baa1a",
              "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
              "type": 2,
              "parentId": "816bf0c1-bf6e-4f34-bfdd-923a98910c5b",
              "code": "16.01",
              "caption": "Изменить",
              "description": null,
              "newGroup": false,
              "toolTip": null,
              "enable": true,
              "visible": true,
              "visibleCondition": null,
              "enableCondition": null,
              "pictureId": null,
              "pictureData": null,
              "pictureKey": null,
              "frameId": null,
              "frameType": 3,
              "kbFrameType": 4,
              "commandId": "166212b1-ea11-4562-9aac-160990e8d474",
              "multiRun": false,
              "expanded": false,
              "positionOrder": 1,
              "selectMenuItemId": null,
              "toolBarPosition": 3,
              "toolBarStyle": 0,
              "items": [],
              "permissions": null
            }
          ],
          "permissions": null
        },
        {
          "id": "399b1665-dc3b-418d-bb0f-9e7011c4d7e4",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 0,
          "parentId": null,
          "code": "17",
          "caption": "Характеристики монтажной стойки",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": false,
          "visibleCondition": "'[IdEqType]' = '17'",
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "36661862-1c2d-4087-a62e-c0dbd47b5752",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 17,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [
            {
              "id": "bd68dbd6-eac1-4440-8214-ab75d996b9d7",
              "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
              "type": 2,
              "parentId": "399b1665-dc3b-418d-bb0f-9e7011c4d7e4",
              "code": "17.01",
              "caption": "Изменить",
              "description": null,
              "newGroup": false,
              "toolTip": null,
              "enable": true,
              "visible": true,
              "visibleCondition": null,
              "enableCondition": null,
              "pictureId": null,
              "pictureData": null,
              "pictureKey": null,
              "frameId": null,
              "frameType": 3,
              "kbFrameType": 4,
              "commandId": "7a84f2da-d424-4958-b5d2-079dbf55a3d0",
              "multiRun": false,
              "expanded": false,
              "positionOrder": 1,
              "selectMenuItemId": null,
              "toolBarPosition": 3,
              "toolBarStyle": 0,
              "items": [],
              "permissions": null
            }
          ],
          "permissions": null
        },
        {
          "id": "f3133b34-7ae8-49a6-ad5e-adde9b558df7",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 0,
          "parentId": null,
          "code": "18",
          "caption": "Характеристики клавиатуры",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": false,
          "visibleCondition": "'[IdEqType]' = '24'",
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "e9fc3cf6-9bfe-4dcb-bcca-2131b338b8f1",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 18,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [
            {
              "id": "2b997b35-2890-4276-be0b-5e9b630d1af6",
              "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
              "type": 2,
              "parentId": "f3133b34-7ae8-49a6-ad5e-adde9b558df7",
              "code": "18.01",
              "caption": "Изменить",
              "description": null,
              "newGroup": false,
              "toolTip": null,
              "enable": true,
              "visible": true,
              "visibleCondition": null,
              "enableCondition": null,
              "pictureId": null,
              "pictureData": null,
              "pictureKey": null,
              "frameId": null,
              "frameType": 3,
              "kbFrameType": 4,
              "commandId": "13a5ac5b-1cdb-4be8-af0a-2eff95f847f2",
              "multiRun": false,
              "expanded": false,
              "positionOrder": 1,
              "selectMenuItemId": null,
              "toolBarPosition": 3,
              "toolBarStyle": 0,
              "items": [],
              "permissions": null
            }
          ],
          "permissions": null
        },
        {
          "id": "21137b38-477d-4d10-acc6-581b2e0a605a",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 0,
          "parentId": null,
          "code": "19",
          "caption": "Характеристики мыши",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": false,
          "visibleCondition": "'[IdEqType]' = '25'",
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "c09e2b2b-4497-4c29-bc21-e6ca2e73196a",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 19,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [
            {
              "id": "bd8a6266-ca41-423f-98fc-29a95aba5e91",
              "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
              "type": 2,
              "parentId": "21137b38-477d-4d10-acc6-581b2e0a605a",
              "code": "19.01",
              "caption": "Изменить",
              "description": null,
              "newGroup": false,
              "toolTip": null,
              "enable": true,
              "visible": true,
              "visibleCondition": null,
              "enableCondition": null,
              "pictureId": null,
              "pictureData": null,
              "pictureKey": null,
              "frameId": null,
              "frameType": 3,
              "kbFrameType": 4,
              "commandId": "4e7713df-b149-4bc3-a465-3ca7dfbbafdf",
              "multiRun": false,
              "expanded": false,
              "positionOrder": 1,
              "selectMenuItemId": null,
              "toolBarPosition": 3,
              "toolBarStyle": 0,
              "items": [],
              "permissions": null
            }
          ],
          "permissions": null
        },
        {
          "id": "87c6a2c7-8616-40b6-b77b-27eb231d5a2f",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 0,
          "parentId": null,
          "code": "20",
          "caption": "Характеристики клавиатрура + мышь",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": false,
          "visibleCondition": "'[IdEqType]' = '23'",
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "c154a736-773d-4e0e-b404-be55d6405678",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 20,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [
            {
              "id": "edddf551-7dfb-4831-921c-1ec55f37e607",
              "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
              "type": 2,
              "parentId": "87c6a2c7-8616-40b6-b77b-27eb231d5a2f",
              "code": "20.01",
              "caption": "Изменить",
              "description": null,
              "newGroup": false,
              "toolTip": null,
              "enable": true,
              "visible": true,
              "visibleCondition": null,
              "enableCondition": null,
              "pictureId": null,
              "pictureData": null,
              "pictureKey": null,
              "frameId": null,
              "frameType": 3,
              "kbFrameType": 4,
              "commandId": "7603ce08-58da-4bf3-b12c-68c9255fb28d",
              "multiRun": false,
              "expanded": false,
              "positionOrder": 1,
              "selectMenuItemId": null,
              "toolBarPosition": 3,
              "toolBarStyle": 0,
              "items": [],
              "permissions": null
            }
          ],
          "permissions": null
        },
        {
          "id": "f2b3864a-bc16-46ac-a1da-0f9b3e69ba20",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 2,
          "parentId": null,
          "code": "21",
          "caption": "Доп. характеристики",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": true,
          "visibleCondition": null,
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "e319874d-84ae-4b38-bbff-c3b34fecc5c8",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 21,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [],
          "permissions": null
        },
        {
          "id": "b9249269-0d89-4dc6-8c00-3774f9b5e9af",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 2,
          "parentId": null,
          "code": "22",
          "caption": "Изображения",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": true,
          "visibleCondition": null,
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "3b8a0668-19be-40c1-9144-dcd23bd533db",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 22,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [],
          "permissions": null
        },
        {
          "id": "b236141f-51dc-4ead-8e57-e396bcd9a2c6",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 2,
          "parentId": null,
          "code": "23",
          "caption": "Комплектующие",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": true,
          "visibleCondition": null,
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "0fb7ce53-dd25-41dc-be16-b4b151d1a7f9",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 23,
          "selectMenuItemId": null,
          "toolBarPosition": 1,
          "toolBarStyle": 1,
          "items": [],
          "permissions": null
        },
        {
          "id": "7408a2fe-f073-496f-b113-8a4ec4dcbe7a",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 2,
          "parentId": null,
          "code": "24",
          "caption": "Хостит оборудование",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": false,
          "visibleCondition": "[IsParent]=true",
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "e882e899-7f2a-4d27-a9f3-1e18aa8a6711",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 24,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [],
          "permissions": null
        },
        {
          "id": "d2a34677-bda8-4e13-a227-25ca70e68b61",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 0,
          "parentId": null,
          "code": "25",
          "caption": "Виртуальные сервера",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": false,
          "visibleCondition": "'[IdEqType]' = '4'",
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "fdf6d7c2-e292-4d38-9ebe-3de6144fb3c1",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 25,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [],
          "permissions": null
        },
        {
          "id": "7b4bfd1b-7ff8-441d-84df-511ca8d36d30",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 0,
          "parentId": null,
          "code": "26",
          "caption": "Установленное ПО",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": true,
          "visibleCondition": null,
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "9a06e7eb-e478-4777-8483-69fd1bf696ae",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 26,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [
            {
              "id": "8869ea16-7282-42a9-934e-2d745a83ca44",
              "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
              "type": 2,
              "parentId": "7b4bfd1b-7ff8-441d-84df-511ca8d36d30",
              "code": "26.01",
              "caption": "Добавить",
              "description": null,
              "newGroup": false,
              "toolTip": null,
              "enable": true,
              "visible": true,
              "visibleCondition": null,
              "enableCondition": null,
              "pictureId": null,
              "pictureData": null,
              "pictureKey": null,
              "frameId": null,
              "frameType": 3,
              "kbFrameType": 4,
              "commandId": "da782515-ab80-440d-afe9-ff9405b8a8f4",
              "multiRun": false,
              "expanded": false,
              "positionOrder": 1,
              "selectMenuItemId": null,
              "toolBarPosition": 3,
              "toolBarStyle": 0,
              "items": [],
              "permissions": null
            }
          ],
          "permissions": null
        },
        {
          "id": "0afdb5ad-acee-4338-97ac-80e8f1c3e335",
          "menuId": "70b6b495-6f58-4adc-85a3-de546b01bfcf",
          "type": 2,
          "parentId": null,
          "code": "27",
          "caption": "Сервера БД",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": true,
          "visibleCondition": null,
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "88cf27b9-827d-4ade-8a78-9bd677e0c169",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 27,
          "selectMenuItemId": null,
          "toolBarPosition": 3,
          "toolBarStyle": 0,
          "items": [],
          "permissions": null
        }
    ];

    treeViewDataSourceTileShort: IMenuItem[] = [
        {
          "id": "163e7a36-4142-4e41-8b57-0f154fd124fe",
          "menuId": "13382adf-eca5-446d-9160-93dfeefd6350",
          "type": 0,
          "parentId": null,
          "code": "04",
          "caption": "Сервера с БД",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": true,
          "visibleCondition": null,
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": 'http://localhost:4200/assets/img/panelbottom_16x16.png',
          "frameId": "1c963c1b-a931-42e2-804b-5356e59fd066",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 4,
          "selectMenuItemId": null,
          "toolBarPosition": 0,
          "toolBarStyle": 0,
          "items": [],
          "permissions": null
        },
        {
          "id": "7ed53655-45e3-4ed8-9d12-b54f79d3b5be",
          "menuId": "13382adf-eca5-446d-9160-93dfeefd6350",
          "type": 0,
          "parentId": null,
          "code": "05",
          "caption": "Документы в разных форматах",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": true,
          "visibleCondition": null,
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": null,
          "frameType": 3,
          "kbFrameType": 4,
          "commandId": "87082ee9-e655-43cc-bc9c-304d88f32989",
          "multiRun": false,
          "expanded": false,
          "positionOrder": 5,
          "selectMenuItemId": null,
          "toolBarPosition": 0,
          "toolBarStyle": 0,
          "items": [],
          "permissions": null
        },
        {
          "id": "83dc6d32-3cd2-4c6f-9450-da7eadb5e83b",
          "menuId": "13382adf-eca5-446d-9160-93dfeefd6350",
          "type": 0,
          "parentId": null,
          "code": "06",
          "caption": "Пользователи тест",
          "description": null,
          "newGroup": false,
          "toolTip": null,
          "enable": true,
          "visible": true,
          "visibleCondition": null,
          "enableCondition": null,
          "pictureId": null,
          "pictureData": null,
          "pictureKey": null,
          "frameId": "e53eab77-179b-4a3d-a1c6-e1d936cd1edd",
          "frameType": 0,
          "kbFrameType": 3,
          "commandId": null,
          "multiRun": false,
          "expanded": false,
          "positionOrder": 6,
          "selectMenuItemId": null,
          "toolBarPosition": 0,
          "toolBarStyle": 0,
          "items": [],
          "permissions": null
        }
    ];

    treeViewSelectItem(item: IMenuItem) {
        console.log(item);
    }
}
